# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options
before_script:
   - eval $(ssh-agent -s)
   - ssh-add <(echo "$SSH_PRIVATE_KEY")
   - mkdir -p ~/.ssh
   - echo "$SSH_SERVER_HOSTKEYS" > ~/.ssh/known_hosts
   - export PATH=$PATH:/usr/local/bin

after_script:
  - killall ssh-agent
  - date

stages:
  - test
  - staging
  - deploy

deploy_master:
  stage: deploy
  environment:
    name: live/$CI_COMMIT_REF_NAME
    url: https://www.gastrojob24.ch
  only:
    - master
  script:
    - dep deploy
  resource_group: prod

deploy_staging:
  stage: staging
  environment:
    name: staging/$CI_COMMIT_REF_NAME
    url: https://staging.gastrojob24.ch
  except:
   - master
  script:
    - dep deploy --branch=$CI_COMMIT_REF_NAME staging
  resource_group: staging

test:
  stage: test
  script:
    - pgrep ssh-agent
    - echo "do some tests"


